name: Daily build

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ballerina-platform/setup-ballerina@v1
      name: Install Ballerina
      with:
        version: 2201.7.2
    - name: status
      working-directory: "app"
      run: ls -la
    - name: user
      working-directory: "app"
      run: echo "$(id -u):$(id -g)"
    - name: Bal Build
      run: docker run -u "root"  -v `pwd`:/home/ballerina ballerina/ballerina:2201.7.2 bal build app
    - name: status
      working-directory: "app"
      run: ls -la
    - name: status
      working-directory: "app"
      run: sudo rm -rf target
    - name: Bal test
      working-directory: "app"
      run: bal test
